[build]
builder = "dockerfile"

[deploy]
startCommand = "java -Xms256m -Xmx512m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Djava.security.egd=file:/dev/./urandom -Dspring.profiles.active=prod -jar /app/app.jar"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments.production.variables]
SPRING_PROFILES_ACTIVE = "prod"
